name: Deploy
on:
  push:
    branches:
      - v4
jobs:
  refreshContent:
    name: Get Latest Content
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: refreshContent
    steps:
      # TODO: Implement this
      - run: exit 0
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script_stop: true
          script: |
            cd www/portfolio
            git checkout .
            git pull
            npm install --production=false
            npm run build
